# Generated by Django 4.0.5 on 2022-07-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0002_cliente_proveedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='cantidad',
            new_name='cant',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='nom_art',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='ape_cliente',
            new_name='ape',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='mail_cliente',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nom_cliente',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='mail_cliente',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nom_proveedor',
            new_name='nom',
        ),
    ]
