# Generated by Django 4.0.5 on 2022-07-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0003_rename_cantidad_articulo_cant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='cliente',
            new_name='clientes',
        ),
        migrations.RenameModel(
            old_name='proveedor',
            new_name='proveedores',
        ),
        migrations.DeleteModel(
            name='articulo',
        ),
    ]
